#!/bin/bash
# ==============================================================================
# 🌐 Proxmox VE 4-Port Multi-NIC Bonding & Direct-Link Setup Script
# ==============================================================================
# - 포트 1, 2, 3: 3Gbps 본딩 그룹 (bond0 / balance-alb) ➔ vmbr0 (192.168.1.200)
# - 포트 4 (미연결): 맥북 1:1 직결 전용 브리지 ➔ vmbr1 (10.10.10.1/24)
# ==============================================================================

set -euo pipefail

# ANSI 색상
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${CYAN}======================================================${NC}"
echo -e "${CYAN}   🌐 Proxmox VE 4-Port Multi-NIC 최적화 설정기       ${NC}"
echo -e "${CYAN}======================================================${NC}"

# Root 권한 체크
if [ "$(id -u)" -ne 0 ]; then
    echo -e "${RED}❌ 이 스크립트는 Proxmox 호스트 root 권한으로 실행해야 합니다.${NC}"
    exit 1
fi

# ifupdown2 패키지 확인 (Proxmox 무중단 네트워크 리로드 필수)
if ! command -v ifreload &> /dev/null; then
    echo -e "${YELLOW}📦 ifupdown2 설치 중...${NC}"
    apt-get update && apt-get install -y ifupdown2
fi

# 물리 이더넷 인터페이스 목록 감지 (en*, eth*)
INTERFACES=($(ls /sys/class/net | grep -E '^(en|eth)' | sort))
NUM_IFACES=${#INTERFACES[@]}

echo -e "${BLUE}🔍 감지된 물리 이더넷 인터페이스 ($NUM_IFACES 개):${NC}"
for iface in "${INTERFACES[@]}"; do
    CARRIER=$(cat /sys/class/net/$iface/carrier 2>/dev/null || echo "0")
    OPERSTATE=$(cat /sys/class/net/$iface/operstate 2>/dev/null || echo "unknown")
    SPEED=$(cat /sys/class/net/$iface/speed 2>/dev/null || echo "N/A")
    
    if [ "$CARRIER" = "1" ] || [ "$OPERSTATE" = "up" ]; then
        STATUS="${GREEN}연결됨 (Link UP, ${SPEED} Mbps)${NC}"
    else
        STATUS="${YELLOW}미연결 (Link DOWN - 맥북 직결 대기)${NC}"
    fi
    echo -e "   - ${CYAN}${iface}${NC}: $STATUS"
done

if [ "$NUM_IFACES" -lt 4 ]; then
    echo -e "${YELLOW}⚠️ 물리 인터페이스가 4개 미만입니다 ($NUM_IFACES 개).${NC}"
    echo -e "계속 진행하려면 감지된 인터페이스를 확인하세요: ${INTERFACES[*]}"
fi

# 기존 네트워크 설정 백업
BACKUP_FILE="/etc/network/interfaces.bak.$(date +%Y%m%d_%H%M%S)"
echo -e "${BLUE}💾 기존 네트워크 설정 백업:${NC} $BACKUP_FILE"
cp /etc/network/interfaces "$BACKUP_FILE"

# 활성화된 인터페이스와 비활성화(맥북 직결용) 인터페이스 분류
ACTIVE_IFACES=()
INACTIVE_IFACES=()

for iface in "${INTERFACES[@]}"; do
    CARRIER=$(cat /sys/class/net/$iface/carrier 2>/dev/null || echo "0")
    if [ "$CARRIER" = "1" ]; then
        ACTIVE_IFACES+=("$iface")
    else
        INACTIVE_IFACES+=("$iface")
    fi
done

# 기본값 결정: 활성화된 인터페이스 3개는 본딩, 남은 1개는 직결
if [ "${#ACTIVE_IFACES[@]}" -ge 3 ]; then
    BOND_SLAVES="${ACTIVE_IFACES[0]} ${ACTIVE_IFACES[1]} ${ACTIVE_IFACES[2]}"
    DIRECT_IFACE="${INACTIVE_IFACES[0]:-${INTERFACES[3]}}"
elif [ "$NUM_IFACES" -ge 4 ]; then
    BOND_SLAVES="${INTERFACES[0]} ${INTERFACES[1]} ${INTERFACES[2]}"
    DIRECT_IFACE="${INTERFACES[3]}"
else
    BOND_SLAVES="${INTERFACES[*]}"
    DIRECT_IFACE=""
fi

echo -e "\n${GREEN}📋 생성될 네트워크 구성 계획:${NC}"
echo -e "   1. ${CYAN}3Gbps 본딩 그룹 (bond0)${NC}: $BOND_SLAVES (모드: balance-alb)"
echo -e "   2. ${CYAN}메인 브리지 (vmbr0)${NC}: 192.168.1.200/24 (게이트웨이: 192.168.1.1) ➔ bond0 연결"
if [ -n "$DIRECT_IFACE" ]; then
    echo -e "   3. ${CYAN}맥북 직결 브리지 (vmbr1)${NC}: 10.10.10.1/24 (게이트웨이 없음) ➔ $DIRECT_IFACE 연결"
fi

echo -e "\n${YELLOW}새로운 /etc/network/interfaces 파일을 생성합니다...${NC}"

# 신규 설정 파일 작성
cat <<INTERFACES_EOF > /etc/network/interfaces
# Proxmox VE 4-Port Multi-NIC Configuration
# Generated by setup_network_bonding_pve.sh on $(date)

auto lo
iface lo inet loopback

INTERFACES_EOF

# 개별 물리 인터페이스 정의
for iface in "${INTERFACES[@]}"; do
cat <<INTERFACES_EOF >> /etc/network/interfaces
iface $iface inet manual

INTERFACES_EOF
done

# bond0 생성
cat <<INTERFACES_EOF >> /etc/network/interfaces
auto bond0
iface bond0 inet manual
	bond-slaves $BOND_SLAVES
	bond-miimon 100
	bond-mode balance-alb

auto vmbr0
iface vmbr0 inet static
	address 192.168.1.200/24
	gateway 192.168.1.1
	bridge-ports bond0
	bridge-stp off
	bridge-fd 0

INTERFACES_EOF

# 맥북 직결용 vmbr1 생성 (4번 포트)
if [ -n "$DIRECT_IFACE" ]; then
cat <<INTERFACES_EOF >> /etc/network/interfaces
auto vmbr1
iface vmbr1 inet static
	address 10.10.10.1/24
	bridge-ports $DIRECT_IFACE
	bridge-stp off
	bridge-fd 0

INTERFACES_EOF
fi

echo -e "${GREEN}✅ /etc/network/interfaces 생성 완료!${NC}"
echo -e "${BLUE}🔄 네트워크 설정을 적용합니다 (ifreload -a)...${NC}"

if ifreload -a; then
    echo -e "\n${GREEN}🎉 네트워크 설정이 성공적으로 적용되었습니다!${NC}"
    echo -e "${CYAN}======================================================${NC}"
    echo -e "1. Proxmox 웹 콘솔: ${GREEN}https://192.168.1.200:8006${NC}"
    echo -e "2. bond0 상태 확인: ${GREEN}cat /proc/net/bonding/bond0${NC}"
    echo -e "3. 맥북 1:1 직결 시:"
    echo -e "   - 맥북 유선 네트워크 설정에서 IP를 ${CYAN}10.10.10.2${NC}, 서브넷 ${CYAN}255.255.255.0${NC} 입력"
    echo -e "   - 맥북에서 ${CYAN}smb://10.10.10.1${NC} 또는 ${CYAN}https://10.10.10.1:8006${NC} 로 즉시 접속 가능"
    echo -e "${CYAN}======================================================${NC}"
else
    echo -e "${RED}⚠️ 네트워크 리로드 중 경고가 발생했습니다. 백업 복구 명령어:${NC}"
    echo -e "   cp $BACKUP_FILE /etc/network/interfaces && ifreload -a"
fi
